### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by tessus** [php/pecl-networking-uuid#6]
I am sorry, but I couldn't find any documentation on the PECL or PHP web site. Where is the documentation that describes the functions this extension provides?

If I missed it, please let me know and point me in the right direction.

P.S.: reading the xml files in the manual dir is not very useful.

**Comment by remicollet** [comment]
Indeed, documentation is missing and have never be merged in official doc

**Comment by tessus** [comment]
I wrote my own uuid v4 function, thus I won't be using this extenstion. However, I am really wondering how people are supposed to use it, if they don't even know the name of the functions....
